Vagrant.configure(2) do |config|
  config.ssh.forward_agent              = true
  config.ssh.username                   = 'deploy'
  config.vm.hostname                    = 'honeybee-agavi-cmf-project.local'
  config.vm.post_up_message             = 'Honeybee CMF DevBox - Happy development!'
  config.vm.box                         = 'berlinonline/opensuse-13_2'
  config.ssh.private_key_path           = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.ssh.insert_key                 = false
  config.vm.network :private_network, type: :dhcp
  config.vm.synced_folder "./", "/vagrant/"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus   = 2
    vb.name   = "honeybee-agavi-cmf-project.local"
    vb.customize [ "modifyvm", :id, "--natdnshostresolver1", "on" ]
    #vb.customize [ "modifyvm", :id, "--natdnsproxy1", "on" ]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path     = "puppets/manifests"
    puppet.manifest_file      = "default.pp"
    puppet.module_path        = "puppets/modules"
    puppet.hiera_config_path  = "puppets/hiera/hiera.yaml"
    puppet.options            = "--debug --parser future --yamldir /vagrant/puppets/hiera"
    puppet.facter = {
      "bo_environment" => "development"
    }
  end

end
