# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: registry.gitlab.berlinonline.net/puppets/berlinonline:latest

build:
  stage: build
  script:
    - make librarian
    - tests/puppet-validate.sh
    - tests/puppet-lint.sh