forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apt'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat', '1.2.3'
mod 'thias-postfix'
mod 'puppetlabs-vcsrepo'
mod 'rodjek-logrotate',
	:git => "https://github.com/rodjek/puppet-logrotate.git"
mod 'camptocamp-openssl',
	:git => "https://github.com/camptocamp/puppet-openssl"
mod 'puppet-nodejs',
	:git => "https://github.com/puppet-community/puppet-nodejs"
mod 'berlinonline-converjon',
	:git => "https://gitlab.berlinonline.net/puppets/converjon.git",
    :ref => '0.2.6'
mod 'berlinonline-couchdb',
	:git => "https://gitlab.berlinonline.net/puppets/couchdb.git",
	:ref => '0.0.5'
mod 'deadpoint-zypprepo',
	:git => "https://github.com/deadpoint/puppet-zypprepo"
mod 'berlinonline-nginx',
	:git => "https://gitlab.berlinonline.net/puppets/nginx.git",
	:ref => '0.0.4'
mod 'berlinonline-elasticsearch',
	:git => "https://gitlab.berlinonline.net/puppets/elasticsearch.git",
	:ref => "0.2.3"
mod 'berlinonline-php',
	:git => "https://gitlab.berlinonline.net/puppets/php.git",
	:ref => '0.2.0'
mod 'berlinonline-phpfpm',
	:git => "https://gitlab.berlinonline.net/puppets/phpfpm.git"
mod 'berlinonline-basics',
	:git => "https://gitlab.berlinonline.net/puppets/basics.git",
	:ref => '0.0.8'
mod 'berlinonline-sudo',
	:git => "https://gitlab.berlinonline.net/puppets/sudo.git",
	:ref => 'production'
mod 'berlinonline-ssh',
	:git => "https://gitlab.berlinonline.net/puppets/ssh.git",
	:ref => '0.0.4.1'
mod 'willdurand-composer'
mod 'fiddyspence/hash_file'
mod 'berlinonline-local_conf',
  :git => 'https://gitlab.berlinonline.net/puppets/local_conf.git',
  :ref => '0.0.5'
mod 'berlinonline-redis',
  :git => "https://gitlab.berlinonline.net/puppets/redis.git",
  :ref => '0.1.0'
mod 'berlinonline-rabbitmq',
  :git => "https://gitlab.berlinonline.net/puppets/rabbitmq.git",
  :ref => '0.2.0'
